### ISSUE TITLE
本地测试无法登陆账户

### ISSUE THREAD

**Issue by idisblueflash** [2remote/yaopai-mobile#114]
找回密码后，仍然不能登录。
用户名: 13552987637
密码：woshifox

**Comment by liubiantao** [comment]
分支 css-icons

无法重现

![image](https://cloud.githubusercontent.com/assets/3268218/11860345/f0ec293c-a4ae-11e5-8c20-3da9c9c2a70a.png)

**Comment by idisblueflash** [comment]
点击登录后，有两个回调数据：

第一个是用户信息，
`{"LoginToken":"","SessionToken":null,"User":{"Id":"18","Name":"纪然","Local":true,"Type":1,"TypeString":"Photographer","Avatar":"http://7xlxo0.com1.z0.glb.clouddn.com/18/e9dc951a-6fb1-4e4a-88d1-7529b1046aad.jpg","Sex":0,"ErrorCode":0,"ErrorMsg":null,"Success":true},"ErrorCode":0,"ErrorMsg":null,"Success":true}`

第二个是登录失败信息。
`{"ErrorCode":-1,"ErrorMsg":"无权访问","Success":false}`

**Comment by liubiantao** [comment]
把node-modules删了重新安装一下。
另外，只需要看代码和图片库就可以改图标了。
剩下的，直接访问m.aiyaopai.com就能解决。

**Comment by idisblueflash** [comment]
发现 Safari不能登录，Chrome可以。 麻烦 @liubiantao 帮忙在Safari下复现一下。

**Comment by idisblueflash** [comment]
看代码和图片库改图标是不是得不到fontSize大小信息？不能预览效果，总觉得不踏实。好在Chrome可以访问了。
