### ISSUE TITLE
如何用AD模块替换摄影师推荐

### ISSUE THREAD

**Issue by idisblueflash** [2remote/yaopai-mobile#125]
目前AD方面后台已经搭建完毕。前面的作品和访谈推荐已经完成：
![2015-12-22 9 46 52](https://cloud.githubusercontent.com/assets/14199/11956491/902fa18c-a8f5-11e5-88fc-ff60ef5a10ad.png)

摄影师却没办法替换，因为横向不是平均切分，不好替换成nxm的方格阵列。

建议：将摄影师部分改成平均切分。

@liubiantao

**Comment by liubiantao** [comment]
先别改，明天跟小夏对接一下，我觉得既然要改就彻底一点，直接改成跟访谈一样，所有方块都是从服务端读取的，不预留「列表页」的入口了。

**Comment by liubiantao** [comment]
![image](https://cloud.githubusercontent.com/assets/3268218/11970671/186824ce-a96a-11e5-86e5-69774252a0e3.png)
![image](https://cloud.githubusercontent.com/assets/3268218/11970672/2117732c-a96a-11e5-8762-597709de3f81.png)

**Comment by idisblueflash** [comment]
经讨论，决定用3x4方式。
