### ISSUE TITLE
用户个人中心主页面

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#157]
![image](https://cloud.githubusercontent.com/assets/3268218/12139130/0f6f1960-b499-11e5-8364-059b3d8484bf.png)

- 联系客服，前端直接写死一个电话号码，点击即可拨打

**Comment by idisblueflash** [comment]
## 用户个人中心主页 时间预估
(2)代表图中蓝色数字， 1H代表一小时。

1. 个人中心页面结构 1H 
1. 更新个人资料页(2) 8H
1. 我的订单需要改现有内容(6) 3H
1. 钱包功能时间未知*

总计： 12H ＝ 3 D， 不包括钱包功能。

**Comment by liubiantao** [comment]
1. 这个issue只包含这一页的结构样式和router，不包括更新个人资料页，钱包等功能。
2. 「更新个人资料页(2) 8H」这两个估的不一样啊。 https://github.com/2remote/yaopai-mobile/issues/160

**Comment by idisblueflash** [comment]
>「更新个人资料页(2) 8H」这两个估的不一样啊。 #160

这个是先粗略估算的 8H（我忘记更新了），详细下来是#160里面的11H。看来，有必要仔细估算。

**Comment by liubiantao** [comment]
用微信的样式库http://weui.github.io/weui/
