### ISSUE TITLE
摄影师个人中心主页面

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#158]
参考 #157 

- 摄影师和用户的个人中心代码需要重构

![image](https://cloud.githubusercontent.com/assets/3268218/12139208/b9b9732a-b499-11e5-8698-1d860817a0ab.png)

**Comment by idisblueflash** [comment]
## 摄影师个人中心 时间预估
(2)代表图中蓝色数字2， 1H代表一小时。

1. 摄影师个人中心 1H 
1. 订单管理(6) 1H
1. 钱包(7) 未知*

总计： 2H ＝ 1 D
