### ISSUE TITLE
摄影师编辑个人资料

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#159]
![image](https://cloud.githubusercontent.com/assets/3268218/12139419/6cf17fc2-b49b-11e5-936d-9231acd039b9.png)

**Comment by idisblueflash** [comment]
## 摄影师编辑个人资料 时间预估
(2)代表图中蓝色数字2， 1H代表一小时。

1. 摄影师编辑个人资料 1H 
1. 头像上传(1) 1H
1. 修改信息(2-5) 4H

总计： 6H ＝ 2 D 
### 参考：
https://xiattst.gitbooks.io/yaopai/content/API/Photographer/ChangePhotographer.html
