### ISSUE TITLE
用户编辑个人资料

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#160]
参考 #159 

![image](https://cloud.githubusercontent.com/assets/3268218/12139449/93a4af86-b49b-11e5-8f40-ad9c5630d953.png)

**Comment by idisblueflash** [comment]
## 用户编辑个人资料 时间预估
(2)代表图中蓝色数字2， 1H代表一小时。

1. 用户编辑个人资料 1H 
1. 头像上传(1) 4H
1. 修改信息(2-3) 2H
1. 修改信息(4) 4H

总计： 11H ＝ 3 D 
### 参考：
 https://xiattst.gitbooks.io/yaopai/content/API/User/ChangeInfo.html
https://xiattst.gitbooks.io/yaopai/content/API/User/ChangeAvatar.html

**Comment by idisblueflash** [comment]
进度会延期2D。

根据实际情况：
1. `3. 修改信息(2-3) 2H ` 估计错误，实际情况是 2 消耗了 4H，预计3也预计需要4H。
2. 第5点也有3H的时间，没有估算进去。
3. 预计完成的 1, 3, 4,5 共7H 约2D，目前预计需要 1+8+4+3 = 16H 约4D

@liubiantao
