### ISSUE TITLE
作品列表页，翻页到第二页之后，再选择标签，第一页的标签就失效了

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#169]
这是没有翻页的时候，正常效果
![image](https://cloud.githubusercontent.com/assets/3268218/12215512/ab0f8fc2-b6fa-11e5-9023-b05640478453.png)

第二页，未选择标签时候的正常效果
![image](https://cloud.githubusercontent.com/assets/3268218/12215516/e07603d0-b6fa-11e5-8f66-02fb17998bf9.png)

在第二页，选择标签之后的灵异事件
![image](https://cloud.githubusercontent.com/assets/3268218/12215521/02b3c234-b6fb-11e5-97a2-38f0a0f4badb.png)

**Comment by idisblueflash** [comment]
这个问题在 561502f38fdf069de12bf7432b4040a432b45980 中有说明。
