### ISSUE TITLE
微信分享

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#182]
文档： https://mp.weixin.qq.com/wiki/7/aaa137b55fb2e0456bf8dd9148dd613f.html#.E9.99.84.E5.BD.951-JS-SDK.E4.BD.BF.E7.94.A8.E6.9D.83.E9.99.90.E7.AD.BE.E5.90.8D.E7.AE.97.E6.B3.95

需求：
移动端web分享作品或者摄影师时，分享的内容描述需进行设置，下图中（我想问问PM图呢？算了，没有图我也懂什么意思）圈红处，例如：针对作品详情页分享标题可设置为【作品标题】，分享内容介绍可设置为【作品简介】；针对摄影师详情页分享标题可设置为【YAOPAI 认证摄影师+摄影师名称】，分享内容介绍可设置成 【摄影师名称+个性签名】，如内容过长可使用......；针对YAOPAI首页的分享标题可设置为【YAOPAI】，分享内容介绍可设置成【YAOPAI ，一个全球预约摄影师的平台】；访谈详情页分享标题可设置成【访谈标题】，分享内容介绍可设置成【访谈标题_YAOPAI 一个全球预约摄影师的平台】；活动详情页分享标题可设置成【活动标题】，分享内容介绍可设置成【活动标题_YAOPAI 一个全球预约摄影师的平台 】

**Comment by idisblueflash** [comment]
## 微信分享 时间预估
(2)代表图中蓝色数字2， 1H代表一小时。

1. 研究微信JSSDK 8H
1. 添加导出标题 4H
总计： 12H ＝ 3 D
