### ISSUE TITLE
摄影师个人主页

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#183]
![image](https://cloud.githubusercontent.com/assets/3268218/12409181/abc04948-bea2-11e5-94f7-fd2a9b21b06f.png)

移动端web摄影师个人主页，地区下建议加上个性签名，下边的摄影师作品封面图片上建议加上价格与作品照片总张数

**Comment by idisblueflash** [comment]
1. 个性签名 1H https://xiattst.gitbooks.io/yaopai/content/API/Photographer/Get.html
1. 价格和总张数信息 参考WorkDetailPage 2H

总计 3H

**Comment by idisblueflash** [comment]
这个页面的入口是哪里？ @liubiantao

**Comment by liubiantao** [comment]
http://m.aiyaopai.com/#/grapherDetail/12?_k=6i7rip
