### ISSUE TITLE
useragent detection

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#195]
参考资料：https://github.com/faisalman/ua-parser-js

需求（只做1，但要考虑到2）：
1. 首页loading动画在安卓上无法正常运行，现在需要判断UA，取消安卓上面的loading动画。
2. 未来可能需要判断是否在微信里面，手机/平板/电脑等，针对性的启用/禁用部分功能。
  - 比如A功能在iOS 8 的微信里面有兼容性问题，并且短时间不好解决，那就禁用它。
  - 比如微信登录，微信分享等功能，只有在微信里面才起作用，如果ua微信，将微信登录换成微博/QQ登录

**Comment by idisblueflash** [comment]
时间预估：
1.  4h
2.  4h
共 8h ＝ 2D
