### ISSUE TITLE
摄影师修改资料保存之后再返回个人中心主页面时，我的主页 一栏没有了

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#231]
莉萍说：原因是跳转路径错了，链接到了普通用户的个人中心主页面了

**Comment by idisblueflash** [comment]
并没有开始做摄影师修改资料 #159 ，所以摄影师能修改，只是个意外。

**Comment by liubiantao** [comment]
哈哈，好，那就简单了，我先禁止掉摄影师修改。

**Comment by liubiantao** [comment]
经测试，摄影师修改资料成功，所以没必要禁用这个功能，加个判断，摄影师保存个人资料的时候返回/grapher_center
