### ISSUE TITLE
设计稿的尺寸

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#258]
![github](https://cloud.githubusercontent.com/assets/14342431/13632781/612c8aa8-e626-11e5-9084-fe8351c66877.png)

此设计稿的尺寸是以Iphone6的大小为基准，宽度是355px。
实际开发中直接用设计稿中的数据有点不妥，毕竟每个手机宽度不都是355px。
琢磨了一个办法是把宽度进行百分比换算：
如果一个div 设计稿中的宽度是20px ，scss里可以这么写:
```css
div {
 width: 20/355)%
}
```
实际上用scss的语法应该是这样的：
```
div {
 width: #{(20/355)%}
}
```
为了简单定义一个全局的scss文件，写一个函数：
```scss
@function st($number){
  @return percentage($number/355);
}
```
然后可以这么写：
```
div {
 width: st(20);
}
```

另外总结：**字体单位用em，图片单位用px，height用px，width用百分比**

大家讨论下，这种办法怎么样

**Comment by stonemakers** [comment]
我查看了淘宝移动端的实现思路，控制两端的宽度为具体值，中间的宽度auto.
