### ISSUE TITLE
摄影师查看的订单详情页中订单信息需完善

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#301]
目前摄影师查看的用户订单详情页中信息不全面，请添加 “预约拍摄日期”和“备注”两项订单信息。

![image](https://dn-shimo-image.qbox.me/OKwakoLXgP01W3rK.png)

**Comment by amile1860** [comment]
这个截图是用户的界面，不是摄影师的界面。所以是要在用户界面还是摄影师界面显示这些？
