### ISSUE TITLE
支付前的订单信息确认页更改订单确认信息

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#306]
支付前的订单信息确认页，请将  “创建时间” 更改为 “拍摄日期” ，后边的日期也做相应的更改
![image](https://cloud.githubusercontent.com/assets/18138853/15034726/216da3a0-12ab-11e6-9260-d83864e94392.png)

**Comment by amile1860** [comment]
相关时间并没有拍摄时间，但是有这些：

- 预约时间
- 订单创建时间
- 订单过期时间

文档在这里：https://xiattst.gitbooks.io/yaopai/content/API/Order/Get.html

代码里显示了这些：

- 创建时间
- 付款时间
- 退款时间
- 发片时间
- 成交时间

是不是要显示预约时间？

**Comment by shirleyandbf** [comment]
需要显示预约时间
