### ISSUE TITLE
重构登陆和注册的样式时遇到的问题

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#320]
花了一整天的时间重构了登陆、注册页面的样式，发现在重复造轮子：
* 首先 redux 版项目（以下暂称第二版）登陆和注册的样式已经做完了，而且里面的 input，button，input-group 样式方面都是花了不少时间组件化过了。
* reflux 版项目（以下暂称第一版）登陆注册设计的和第二版一模一样，为什么又重新写了一遍样式？
* 当我把第一版重新写的样式重构完之后发现，input，button, input-group 又该组件化了……

总结：
1. 应该把第二版造过得轮子搬到第一版，至少 CSS 部分搬过去是没问题，这个工作由我来主做，石头配合
2. 登陆和注册页面的样式我决定还是用第二版已经组件化过的（第一版接下来的设计，input，button 应该都会统一用第二版的 input，button 样式吧？）
3. 下周一完成上面总结的 1，2 工作
4. 石头考虑下怎样合理的设计第一版的 `_variables.scss`，可以自己用第二版的 `_variables.scss ` 吗？

**Comment by stonemakers** [comment]
1.第二版项目的样式并没有完全写好，按钮的放置和提示框都没有完善。
2.直接改样式比拿过来之前的，再改更麻烦。时间上考虑直接改更快。

总结
现在你可以花时间去组件化了。目的就是快速让大家测试，现在已经可以测试，你慢慢优化就行。
