### ISSUE TITLE
app/components/UserCenterPage 这个目录下发现了不该有订单页面

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#327]
@liubiantao 
`app/components/UserCenterPage` 这个目录下，文件名包含 `Ticket` 的是订单相关的页面，这是我和 @amile1860  做订单之前遗留下来的老文件吗？
`app/index.js ` 里也有跳转到「老订单」页面的路由比如： localhost:8080/#/user_tickets
由于涉及到的文件加上路由挺多的，故发个 Issues

@amile1860 交给你了，把没用的东西删了，路由精简下？

**Comment by amile1860** [comment]
@zaxlct 可能是咱来之前他们做的订单页吧？咱那时候没用到ticket这个词好像。我卡在摄影师端这了，你删一下吧。😂
