### ISSUE TITLE
用什么话提示用户「登录后才能关注」更好？

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#363]
![image](https://cloud.githubusercontent.com/assets/14342431/16226412/e43be426-37dd-11e6-9566-2524180eaed9.png)

----
我这句话太 LOW ！

**Comment by a11266897** [comment]
关注？登录。

**Comment by liubiantao** [comment]
关注 ? 登录 ：" "
@a11266897

**Comment by shirleyandbf** [comment]
参考了很多，在未登录状态下点击「关注」一般都直接跳转至登录页面，不用提示。

**Comment by zaxlct** [comment]
> 1、参考了很多，在未登录状态下点击「关注」一般都直接跳转至登录页面或在当前页弹出登录窗口进行登录，不用提示。所以咱们这里也不用提示了。
> 2、登录后继续进行之前的关注操作

我觉得可能用户不想登录，随手点击了一下直接跳到登录页面是不友好的（我自己也很烦直接跳到登录页面的逻辑）,不过这个由你决定 ：)
