### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#379]
![wechat_1466824809](https://cloud.githubusercontent.com/assets/14342431/16354446/d1c63fa8-3ac6-11e6-9619-dd8491d650b9.jpeg)

SourceMap 好像坏了……
你们都没发现吗

**Comment by zaxlct** [comment]
偶尔会坏，不知道是不是只有我遇到这种情况：(

**Comment by liubiantao** [comment]
是的，偶尔会有问题，刷新几次就好了
