### ISSUE TITLE
path 应该保存为常量

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#394]
![image](https://cloud.githubusercontent.com/assets/14342431/16440591/0523a87c-3df6-11e6-85d3-7282a7418aa7.png)

path 应该保存为常量，单独一个文件存放，这样随便改动一个 path，也不至于项目挂了。例如：
```javascript
const GRAHER_DETAIL = `grapher_detail`;
```

**Comment by liubiantao** [comment]
没必要吧，这跟单独一个文件没什么区别，代码还更少一点。
