### ISSUE TITLE
iOS 分享到微信的 url 异常

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#398]
![image](https://cloud.githubusercontent.com/assets/3268218/16474807/6c8369b0-3eac-11e6-96d6-c5789bb3d1cd.png)
微信识别成了 iframe 里面 ping++ 的 url。
考虑把支付的 js 做成动态的，只有到支付的时候才插入这段 js

**Comment by zaxlct** [comment]
动态的 JS？ PHP 可以吧

**Comment by liubiantao** [comment]
> 动态的 JS？ PHP 可以吧

直接用 document.write() 吧
