### ISSUE TITLE
完善搜索框中的默认提示

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#439]
1、作品列表页的搜索框中默认提示内容修改为：“搜索 作品名称/作品标签/摄影师昵称”

2、摄影师列表页的搜索框中默认提示内容修改为：“搜索 摄影师昵称/地区”

**Comment by zaxlct** [comment]
I do

**Comment by liubiantao** [comment]
@shirleyandbf @zaxlct
我突然想起来，这个提示应该从后台设置，然后前端读取就好了，这样提示文字可以跟 iOS 保持一致。
下周做筛选的时候我会把它改为从后台读取。

**Comment by zaxlct** [comment]
good
