### ISSUE TITLE
作品筛选、摄影师筛选 优化方案

### ISSUE THREAD

**Issue by stonemakers** [2remote/yaopai-mobile#446]
问题描述：
1. 当点击筛选时，向下的箭头旋转朝上
2. 页面增加遮罩层，并且当点击遮罩层的时候，筛选框自动收回。
3. 【bug】iphone6 百度输入法 点击搜索框，直接（搜索栏连同筛选列表）下移错位，但是作品列表不影响。（问题在导航栏fixed 状态上）
![2 pic](https://cloud.githubusercontent.com/assets/17716867/16682170/a348e2ec-452b-11e6-986c-f759d6a11a20.jpg)

**Comment by liubiantao** [comment]
@zaxlct 我先把第2条暂时修复一下，下周要整个调整筛选样式，没必要浪费太多精力。
#448
