### ISSUE TITLE
登录/注册页面bug汇总以及修改建议

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#463]
**bug：**
1、登录入口与输入面板重叠，测试机型：oppo  r7、Letv x501
![image](https://cloud.githubusercontent.com/assets/18138853/16829875/fd7e5c8c-49cd-11e6-984d-626ffc3891dc.png)

2、登录页面显示不全，1.3iPhone SE登录界面不显示  型号：9.3.2（14F69）
![image](https://cloud.githubusercontent.com/assets/18138853/16829889/1e6d5d8a-49ce-11e6-8d35-4b4ddf27b567.png)
![image](https://cloud.githubusercontent.com/assets/18138853/16829899/2a666d02-49ce-11e6-9367-efdc9d91a136.png)

**修改建议**
1、更改登录账号输入框type；
2、更改登录输入框的默认提示为： “手机号/邮箱”
3、登录页面中「YAOPAI 服务条款」处请更改为「注册新用户」并链接到注册的页面
4、注册页面注册按钮上添加「点击注册表示同意《服务条款》」，「《服务条款》」链接至原来的服务条款页面
![image](https://cloud.githubusercontent.com/assets/18138853/16829926/520970ac-49ce-11e6-9807-e25684e7fdd7.png)

PS：这两天网络不好，图片一直上传不上去，上午发了好几遍，这次终于发上去了

**Comment by zaxlct** [comment]
总算是解决了
