### ISSUE TITLE
VM2883:1 Uncaught SyntaxError: Unexpected token q in JSON at position 1

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#470]
![image](https://cloud.githubusercontent.com/assets/14342431/16836115/792498ae-49ee-11e6-8e04-2ee2bf8bcb1f.png)

功能能正常使用，但是防止以后为自己挖坑，抽空解决下吧

**Comment by liubiantao** [comment]
搞不定……
