### ISSUE TITLE
个人中心修改资料，上传头像异常

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#475]
上传头像

**Comment by zaxlct** [comment]
I DO

**Comment by shirleyandbf** [comment]
![image](https://cloud.githubusercontent.com/assets/18138853/17315462/4e267f00-589e-11e6-8501-8488594d5005.png)

上传头像还是有问题，修改用户头像有单独的接口：User.ChangeAvatar

**Comment by zaxlct** [comment]
小夏说：
 dev.api.aiyaopai.com/file/token ： 字符串
dev.api.yaopai.com/?api=file.token : JSON

**Comment by zaxlct** [comment]
SOS
