### ISSUE TITLE
Hi~the readMe

### ISSUE THREAD

**Issue by weitest123** [2remote/yaopai-mobile#485]
拉面神教什么鬼

**Comment by zaxlct** [comment]
> 拉面神教什么鬼    

参考 [拉面神教](http://baike.baidu.com/link?url=KUF_Ow3AmFDiHSskB75d-pH7nPx4N_L_nf_BOHqM5xBBzW_CRnZITfwX6iu8u6dnHpyJbJ1mYrhFbyg676yZIGQX26dLCtpWEu2XrfcF3rW)

没什么乱用，只是觉得好玩——不然只敲代码是一件多无聊的事~

**Comment by liubiantao** [comment]
保佑我们没有 bug 啊

**Comment by weitest123** [comment]
啊劳动法士大夫
