### ISSUE TITLE
搜索页面无法滚动，影响部分机型用户体验

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#498]
![image](https://cloud.githubusercontent.com/assets/18138853/17096250/03248cd6-528b-11e6-9e10-70b9b690ab23.png)

测试机型：iPhone 5 ，iPhone 5s

**Comment by liubiantao** [comment]
减少标签数量，等新版筛选完全做好再添加回来

**Comment by shirleyandbf** [comment]
主要是 APP 那边需要展示海外那些地区，要不然管理后台直接可以设置不显示的
