### ISSUE TITLE
更改「获取验证码」的位置

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#528]
1、手机注册页面「获取验证码」的位置如下图
![image](https://cloud.githubusercontent.com/assets/18138853/17425274/ebfbe114-5afd-11e6-921a-639ca61eb6be.png)

2、邮箱注册页面更改「获取邮箱验证码」的位置如下图
![image](https://cloud.githubusercontent.com/assets/18138853/17425320/8456e9ae-5afe-11e6-871f-d869c3d6cd2b.png)

**Comment by zaxlct** [comment]
这个还真没注意过……
