### ISSUE TITLE
【新增需求】Web APP 推荐 IOS 用户下载 APP

### ISSUE THREAD

**Issue by shirleyandbf** [2remote/yaopai-mobile#560]
推荐位置：「作品列表页」、「摄影师列表页」、「作品详情页」和「摄影师个人主页」底部 增加 「下载 APP 联系摄影师」的入口

![image](https://cloud.githubusercontent.com/assets/18138853/17999641/a62c8278-6bac-11e6-9f8d-ca70fc240421.png)

APP 下载链接为：http://a.app.qq.com/o/ioslink.jsp?id=1105711466

**Comment by liubiantao** [comment]
为什么微信内-> 已安装 不选择直接打开 app

你体验一下这个：http://www.bilibili.com/mobile/video/av5780343.html

![image](https://cloud.githubusercontent.com/assets/3268218/18003026/d991209a-6bbd-11e6-8728-061a272dafb8.png)

**Comment by shirleyandbf** [comment]
如果能像哔哩哔哩这样直接打开更好，主要是看了简书、知乎、网易云这些打开的话还需要走「在浏览器中打开」这一步，不知是微信内有限制还是其他技术原因？所以也加了这一步，如果咱们能在微信内直接打开的话对用户来说就更方便了，就可以省去这一步。
