### ISSUE TITLE
国家、省、城市 三级筛选组件代码，大家 Review 下！

### ISSUE THREAD

**Issue by zaxlct** [2remote/yaopai-mobile#570]
<img width="1000" alt="default" src="https://cloud.githubusercontent.com/assets/14342431/18223492/518b93e0-71eb-11e6-9baa-398d9cc8a739.png">

这是数据的脑图 😂

**Comment by zaxlct** [comment]
```javascript
import {data} from './data.js';

class App extends React.Component {
	constructor(props) {
		super(props);
		this.state = {
			itemNode: <li></li>
		}
	}

	componentDidMount() {
		let itemNode = data.map((country, index) => (
			<li key={index} onClick={() => this.provinceListRender.bind(this)(country.Provinces)}>{country.Cn}</li>
		))
		this.setState({itemNode});
	}

	provinceListRender(provinceData) {
		if(provinceData.length == 1) { // 这个国家只有一个省
			 this.cityListRender.bind(this)(provinceData[0].Cities);
			 return;
		}
		let itemNode = provinceData.map((province, index) => (
			<li key={index} onClick={() => this.cityListRender.bind(this)(province.Cities)}>{province.Cn}</li>
		))
		this.setState({itemNode});
	}

	cityListRender(cityData) {
		if(cityData.length == 1) { // 这个省只有一个市
			this.selectResult.bind(this)(cityData[0].Id)
		}
		let itemNode = cityData.map((city, index) => (
			<li key={index} onClick={() => this.selectResult.bind(this)(city.Id)}>{city.Cn}</li>
		))
		this.setState({itemNode});
	}

	selectResult(Id) {
		// 筛选完成发送 Id 给小夏
		console.log(Id);
	}

	render() {
		return (
			<div>
				<ul>
					{this.state.itemNode}
				</ul>
			</div>
		);
	}
}
```

**Comment by zaxlct** [comment]
不知道是不是有个别国家连省都没有，只有一个国家名的。我再加个判断吧……

**Comment by amile1860** [comment]
看不懂。简单说明一下data.js的结构和这个组件想达到的目的吧。顺便还有这个组件的简单实现思路？

**Comment by zaxlct** [comment]
容我整理下思路

**Comment by zaxlct** [comment]
### 数据结构
 首先应看一下小夏发的含有国家省城市资料的 JSON 文件，配合上面我发的脑图，大致了解一下这个文件的层级结构。

### 实现思路
country => province => city

1. 首先 `render` 一个`country list` 出来：通过`componentDidMount()`把 `country list` 存在 `this.state.itemNode` 里，同时给每条 `country` （`li`标签）加一个点击事件，并把 `country` 传递给下一个方法`provinceLsitRender`。
2. 记录一下选择的国家，存到 `this.state.province`里，然后判断这个国家有没有省，
再把这个国家里所有的省`render` 一个 `province list ` 出来，加一个点击事件，传递数据给下一个方法`cityListRender`。
3. `cityListRender` 在这个方法里记录一下选择的省，做一下判断，然后`render`一个`city list`，最后把城市的 `id` 传递出去。

筛选完毕后，`{country, province, city} = this.state` 存放着筛选的记录。

**Comment by amile1860** [comment]
数据结构从XML/JSON整理到data.js之后是什么样的？理论上可以知道是 *国家>省份>城市* 的3层结构，你调整之后的结构是什么？

然后组件的基本思路，大概是要满足什么样的条件？比如我能想到的是：

- 组件复用：需要组件可以添加一个类似于 `onChange` 的回调，组件会把用户选择结果反馈出去
- 样式复用：是已经给组件内置了className，我们自己写样式，还是传入固定的样式选项

**Comment by zaxlct** [comment]
* 数据结构：没做任何处理，我拿到的原始数据是小夏发我的 JSON 文件，然后全部拷贝到了 `data.js`里。
![301662fbb9d56df6b876130e1bfe2a5e](https://cloud.githubusercontent.com/assets/14342431/18224517/a630529a-720a-11e6-9ac2-df5533c6ec26.jpg)

* 样式：看上图，微信的逻辑是在一个新的页面打开，移动端可以这个样子做，而且能直接用 weui.css。但是我没考虑到 PC 端总不能也进入一个新页面再筛选吧，当然也不可能用 weui.css。总之不太能确定样式，还是需要和石头讨论下。

* 回调：`selectReslut` 方法能拿到最终的结果，可以在里面写回调。
能拿到这几个数据：
    1. 用户选择的国家，城市，地区（字符串）
    2. 用户最终选择的城市 Id （发给后台）

* 组件传参：应该传一个地区的初始值，也就是上一次用户的筛选数据。

* 不知道 PC 端是不是也有修改性别，昵称，头像的功能，我觉得这些都能共用。具体还是需要交流一下。

**Comment by amile1860** [comment]
问题的重点在于：

- data.js的具体结构到底是什么，你整理明白之后简单说明一下
- 组件的功能复用是想在不同的地方使用，所以要把你写的组件暴露出来的API和相应的限制说明白
- 样式的复用：很明显是想多个系统下使用，所以才叫“复用”。组件设计的时候就要考虑好怎么为样式留有余地，否则你为mobile配置好了样式，我拿来用的时候再给你改坏了，就不能算复用了

所以

- 所谓“整理”地区文件，就是要有一个基本结构的描述
- 所谓“写一个组件”就是为了**复用**

P.S. 记得惦记着点Redux的思路，不然以后换过去Redux就又要调整。

比如你可以参考[这个](https://github.com/ant-design/ant-design/blob/master/components/select/index.zh-CN.md)

**Comment by zaxlct** [comment]
这个参考真不错，我考虑的不周到，抽时间再重构下
