### ISSUE TITLE
标签

### ISSUE THREAD

**Issue by liubiantao** [2remote/yaopai-mobile#96]
- 分为两行：第一行城市，第二行风格。
- 所有的标签都允许多选，点完任何一个标签，立刻显示结果，结果为交集。

![image](https://cloud.githubusercontent.com/assets/3268218/11712020/69058f84-9f65-11e5-9cf5-bc98a7f0a82b.png)
![image](https://cloud.githubusercontent.com/assets/3268218/11712024/6f589dd6-9f65-11e5-94fb-fcb3bcfe1227.png)

**Comment by idisblueflash** [comment]
close with #168

**Comment by idisblueflash** [comment]
#168
